gorm = "gorm.io/gorm"
gin = "github.com/gin-gonic/gin"
fiber = "github.com/gofiber/fiber/v2"
echo = "github.com/labstack/echo/v4"
chi = "github.com/go-chi/chi/v5"
cobra = "github.com/spf13/cobra"
viper = "github.com/spf13/viper"
zap = "go.uber.org/zap"
logrus = "github.com/sirupsen/logrus"
testify = "github.com/stretchr/testify"

